
const CONSTANTS={
   INITIAL_APPOINTMENTS:'INITIAL_APPOINTMENTS',
   ADD_APPOINTMENTS:'ADD_APPOINTMENTS',
   EDITE_APPOINTMENT:'EDITE_APPOINTMENT',
   DELETE_APPOINTMENT:'DELETE_APPOINTMENT'

}

export  default CONSTANTS