
const CONSTANTS={
   INITIAL_APPOINTMENTS:'INITIAL_APPOINTMENTS',
   ADD_APPOINTMENTS:'ADD_APPOINTMENTS',
   EDIT_APPOINTMENT:'EDIT_APPOINTMENT',
   DELETE_APPOINTMENT:'DELETE_APPOINTMENT'

}

export  default CONSTANTS